#!/bin/bash
# Run Pallas tests of interest
# Usage: ./pallas_tests_of_interest.sh [additional pytest args]

set -e

export TORCHINDUCTOR_FORCE_DISABLE_CACHES=1

# Test filter - all tests of interest joined with 'or'
TEST_FILTER="
    test__unsafe_masked_index_cpu_pallas or
    test__unsafe_masked_index_put_accumulate_cpu_pallas or
    test_add_complex_strided_fallback_cpu_pallas or
    test_add_inplace_permuted_cpu_pallas or
    test_arange1_cpu_pallas or
    test_arange2_cpu_pallas or
    test_arange3_cpu_pallas or
    test_arange4_cpu_pallas or
    test_arange5_cpu_pallas or
    test_arange6_cpu_pallas or
    test_arange_multi_output or
    test_as_strided_cpu_pallas or
    test_as_strided_on_views_cpu_pallas or
    test_as_strided_scatter_cpu_pallas or
    test_assert_size_stride_op_name_fail_cpu_pallas or
    test_assert_size_stride_op_name_pass_cpu_pallas or
    test_bucketize_broadcast_cpu_pallas or
    test_buffer_copied_in_graph_with_different_shapes_cpu_pallas or
    test_cat_empty_index_cpu_pallas or
    test_check_stack_no_cycles_cpu_pallas or
    test_complex_indexing_2d or
    test_complex_indexing_gather or
    test_constant_pad_2d_strides_nonpositive_cpu_pallas or
    test_contiguous_index_validation or
    test_conv1d_with_permute_cpu_pallas or
    test_conv_shape_check_cpu_pallas or
    test_conv_transpose_zero_size_output_cpu_pallas or
    test_conv_with_as_strided_cpu_pallas or
    test_dense_mask_index_cpu_pallas or
    test_different_shapes or
    test_dtypeview_float16_float16_cpu_pallas or
    test_dtypeview_float16_float32_cpu_pallas or
    test_dtypeview_float16_float64_cpu_pallas or
    test_dtypeview_float16_int16_cpu_pallas or
    test_dtypeview_float16_int32_cpu_pallas or
    test_dtypeview_float16_int64_cpu_pallas or
    test_dtypeview_float16_int8_cpu_pallas or
    test_dtypeview_float16_uint8_cpu_pallas or
    test_dtypeview_float32_float16_cpu_pallas or
    test_dtypeview_float32_float32_cpu_pallas or
    test_dtypeview_float32_float64_cpu_pallas or
    test_dtypeview_float32_int16_cpu_pallas or
    test_dtypeview_float32_int32_cpu_pallas or
    test_dtypeview_float32_int64_cpu_pallas or
    test_dtypeview_float32_int8_cpu_pallas or
    test_dtypeview_float32_uint8_cpu_pallas or
    test_dtypeview_float64_float16_cpu_pallas or
    test_dtypeview_float64_float32_cpu_pallas or
    test_dtypeview_float64_float64_cpu_pallas or
    test_dtypeview_float64_int16_cpu_pallas or
    test_dtypeview_float64_int32_cpu_pallas or
    test_dtypeview_float64_int64_cpu_pallas or
    test_dtypeview_float64_int8_cpu_pallas or
    test_dtypeview_float64_uint8_cpu_pallas or
    test_dtypeview_fusion_cpu_pallas or
    test_dtypeview_int16_float16_cpu_pallas or
    test_dtypeview_int16_float32_cpu_pallas or
    test_dtypeview_int16_float64_cpu_pallas or
    test_dtypeview_int16_int16_cpu_pallas or
    test_dtypeview_int16_int32_cpu_pallas or
    test_dtypeview_int16_int64_cpu_pallas or
    test_dtypeview_int16_int8_cpu_pallas or
    test_dtypeview_int16_uint8_cpu_pallas or
    test_dtypeview_int32_float16_cpu_pallas or
    test_dtypeview_int32_float32_cpu_pallas or
    test_dtypeview_int32_float64_cpu_pallas or
    test_dtypeview_int32_int16_cpu_pallas or
    test_dtypeview_int32_int32_cpu_pallas or
    test_dtypeview_int32_int64_cpu_pallas or
    test_dtypeview_int32_int8_cpu_pallas or
    test_dtypeview_int32_uint8_cpu_pallas or
    test_dtypeview_int64_float16_cpu_pallas or
    test_dtypeview_int64_float32_cpu_pallas or
    test_dtypeview_int64_float64_cpu_pallas or
    test_dtypeview_int64_int16_cpu_pallas or
    test_dtypeview_int64_int32_cpu_pallas or
    test_dtypeview_int64_int64_cpu_pallas or
    test_dtypeview_int64_int8_cpu_pallas or
    test_dtypeview_int64_uint8_cpu_pallas or
    test_dtypeview_int8_float16_cpu_pallas or
    test_dtypeview_int8_float32_cpu_pallas or
    test_dtypeview_int8_float64_cpu_pallas or
    test_dtypeview_int8_int16_cpu_pallas or
    test_dtypeview_int8_int32_cpu_pallas or
    test_dtypeview_int8_int64_cpu_pallas or
    test_dtypeview_int8_int8_cpu_pallas or
    test_dtypeview_int8_uint8_cpu_pallas or
    test_dtypeview_uint8_float16_cpu_pallas or
    test_dtypeview_uint8_float32_cpu_pallas or
    test_dtypeview_uint8_float64_cpu_pallas or
    test_dtypeview_uint8_int16_cpu_pallas or
    test_dtypeview_uint8_int32_cpu_pallas or
    test_dtypeview_uint8_int64_cpu_pallas or
    test_dtypeview_uint8_int8_cpu_pallas or
    test_dtypeview_uint8_uint8_cpu_pallas or
    test_empty_strided_cpu_pallas or
    test_exact_stride_cpu_pallas or
    test_expand_as_cpu_pallas or
    test_expand_clone or
    test_expand_cpu_pallas or
    test_expand_merged_dims or
    test_expanded_reduction_cpu_pallas or
    test_float_index_expression_cpu_pallas or
    test_float_index_expression_type_promotion_cpu_pallas or
    test_float_repr_dynamic_shapes_cpu_pallas or
    test_full_like_transposed_cpu_pallas or
    test_gather_scatter_cpu_pallas or
    test_generated_code_has_size_stride_assert_cpu_pallas or
    test_graph_partition_arange1_cpu_pallas or
    test_graph_partition_arange2_cpu_pallas or
    test_grid_sampler_expand_preserves_view_cpu_pallas or
    test_index1_cpu_pallas or
    test_index2_cpu_pallas or
    test_index3_cpu_pallas or
    test_index_dynamic_shapes_cpu_pallas or
    test_index_float_zero_cpu_pallas or
    test_index_propagation_abs_cpu_pallas or
    test_index_propagation_cpu_pallas or
    test_index_propagation_device_assert_masked_cpu_pallas or
    test_index_propagation_flip_cpu_pallas or
    test_index_propagation_floordiv_cpu_pallas or
    test_index_propagation_nested_indirect_indexing_cpu_pallas or
    test_index_propagation_remainder_cpu_pallas or
    test_index_put1_cpu_pallas or
    test_index_put2_cpu_pallas or
    test_index_put3_cpu_pallas or
    test_index_put4_cpu_pallas or
    test_index_put_as_masked_fill_cpu_pallas or
    test_index_put_deterministic_fallback_cpu_pallas or
    test_index_put_failed_reinplace_cpu_pallas or
    test_index_put_fallback1_cpu_pallas or
    test_index_put_fallback2_cpu_pallas or
    test_index_put_index_cpu_pallas or
    test_index_put_reinplace_cpu_pallas or
    test_index_remainder_cpu_pallas or
    test_index_select_cpu_pallas or
    test_index_tensor_cpu_pallas or
    test_indirect_load_broadcast_cpu_pallas or
    test_inner_fn_str_and_stride_cpu_pallas or
    test_insignificant_strides_cpu_pallas or
    test_int_input_dynamic_shapes_cpu_pallas or
    test_large_broadcast_reduction_cpu_pallas or
    test_large_strided_reduction_cpu_pallas or
    test_linalg_eig_stride_consistency_cpu_pallas or
    test_lite_dynamic_shape_assertion_cpu_pallas or
    test_llama3 or
    test_masked_scatter_cpu_pallas or
    test_mix_device_index_cpu_pallas or
    test_mm_views_cpu_pallas or
    test_move_arange_cpu_pallas or
    test_mul_index_expr_cpu_pallas or
    test_multi_gpu_recompile_on_index_cpu_pallas or
    test_needs_contiguous_strides_cpu_pallas or
    test_neg_index_cpu_pallas or
    test_new_empty_strided_cpu_pallas or
    test_nonzero_static_stride_cpu_pallas or
    test_output_strides_cpu_pallas or
    test_pad_view_cpu_pallas or
    test_permute1_cpu_pallas or
    test_permute2_cpu_pallas or
    test_pow_by_natural_log2_dynamic_shapes_cpu_pallas or
    test_reinterpret_dtypeview_cpu_pallas or
    test_remove_noop_slice_scatter_cpu_pallas or
    test_remove_noop_view_default_cpu_pallas or
    test_remove_noop_view_dtype_cpu_pallas or
    test_repeat_as_strided_cpu_pallas or
    test_require_stride_expanded_cpu_pallas or
    test_rope_repeat_kv_transpose or
    test_rope_transpose_contiguous or
    test_rsqrt_dynamic_shapes_cpu_pallas or
    test_scatter1_cpu_pallas or
    test_scatter2_cpu_pallas or
    test_scatter3_cpu_pallas or
    test_scatter4_cpu_pallas or
    test_scatter5_cpu_pallas or
    test_scatter6_cpu_pallas or
    test_scatter_add1_cpu_pallas or
    test_scatter_add2_cpu_pallas or
    test_scatter_add3_cpu_pallas or
    test_scatter_bf16_cpu_pallas or
    test_scatter_reduce1_cpu_pallas or
    test_scatter_reduce2_cpu_pallas or
    test_scatter_reduce3_cpu_pallas or
    test_searchsorted_broadcast_cpu_pallas or
    test_select_scatter_cpu_pallas or
    test_select_scatter_dtype_consistency_cpu_pallas or
    test_shape_padding_cpu_pallas or
    test_shape_prop_torch_ones_cpu_pallas or
    test_slice_scatter2_cpu_pallas or
    test_slice_scatter3_cpu_pallas or
    test_slice_scatter4_cpu_pallas or
    test_slice_scatter5_cpu_pallas or
    test_slice_scatter_cpu_pallas or
    test_slice_scatter_dtype_consistency_cpu_pallas or
    test_slice_scatter_reinplace_cpu_pallas or
    test_slice_view_with_graph_break_cpu_pallas or
    test_sort_transpose_cpu_pallas or
    test_split_cumsum_index_cpu_pallas or
    test_split_reduction_dynamic_shape_cpu_pallas or
    test_sqrt_dynamic_shapes_cpu_pallas or
    test_stack_cpu_pallas or
    test_stride_expanded_tensors or
    test_stride_multiple_inputs or
    test_stride_non_contiguous_1d or
    test_stride_non_contiguous_2d_both_stride or
    test_stride_non_contiguous_2d_col_stride or
    test_stride_non_contiguous_2d_row_stride or
    test_stride_non_contiguous_2d_transpose or
    test_stride_non_contiguous_3d or
    test_stride_non_contiguous_as_strided or
    test_stride_non_contiguous_channels_last or
    test_stride_non_contiguous_diagonal or
    test_stride_non_contiguous_dtypes or
    test_stride_non_contiguous_permuted or
    test_stride_non_contiguous_select_stride or
    test_stride_non_contiguous_unsqueeze or
    test_stride_preservation_with_stride_modifying_fx_pass_cpu_pallas or
    test_strided_2d_pallas or
    test_strided_inputs_cpu_pallas or
    test_strided_int_pallas or
    test_strided_offset_pallas or
    test_tensor_index_put_slice_cpu_pallas or
    test_tensor_index_slice_cpu_pallas or
    test_transpose_add_cpu_pallas or
    test_transpose_cpu_pallas or
    test_transpose_noncontiguous_input or
    test_transposed_propagates_cpu_pallas or
    test_triton_argmin_argmax_transpose_logical_index_cpu_pallas or
    test_view_as_complex_cpu_pallas or
    test_view_as_real_cpu_pallas or
    test_view_copy_dtype_change_cpu_pallas or
    test_view_detach_cpu_pallas or
    test_view_dtype_0d_smaller_to_larger_element_size_cpu_pallas or
    test_view_on_aliased_cpu_pallas or
    test_view_uint8_through_differing_bitwidths_cpu_pallas or
    test_views1_cpu_pallas or
    test_views2_cpu_pallas or
    test_views3_cpu_pallas or
    test_views4_cpu_pallas or
    test_views5_cpu_pallas or
    test_views6_cpu_pallas or
    test_views7_cpu_pallas or
    test_where_broadcast_cpu_pallas or
    false_placeholder_never_matches
"

# Remove newlines and extra spaces from filter
TEST_FILTER=$(echo "$TEST_FILTER" | tr '\n' ' ' | sed 's/  */ /g')

echo "Running Pallas tests of interest..."
echo "Log file: /tmp/pallas_tests_full.log"

python -m pytest test/inductor/test_pallas.py -v -k "$TEST_FILTER" "$@" 2>&1 | tee /tmp/pallas_tests_full.log

echo ""
echo "Test run complete. Results saved to /tmp/pallas_tests_full.log"
